create table if not exists analytics (
        id bigint generated by default as identity,
        comments_count integer not null,
        engaged_count integer not null,
        follows_count integer not null,
        posts_count integer not null,
        reached_count integer not null,
        save_count integer not null,
        shares_count integer not null,
        stories_count integer not null,
        social_account_id bigint,
        primary key (id)
    );

 create table if not exists social_media_account (
        id bigint generated by default as identity,
        followers_count integer not null,
        following_count integer not null,
        platform varchar(255),
        posts_count integer not null,
        user_id bigint,
        primary key (id)
    );

create table if not exists tb_users (
        id bigint generated by default as identity,
        bio varchar(255),
        category varchar(255),
        contact_options varchar(255),
        links varchar(255),
        name varchar(255),
        primary key (id)
    );

--insert dummy data
INSERT INTO tb_users (id, name, category, bio, contact_options, links)
VALUES (1, 'Ganesha', 'Influencer', 'Bio of Ganesha', 'email@example.com', 'https://example.com');
INSERT INTO tb_users (id, name, category, bio, contact_options, links)
VALUES (2, 'Puneeth M', 'Actor', 'Bio of Puneeth M', 'email@example.com', 'https://example.com');

INSERT INTO social_media_account (id, user_id, platform, followers_count, following_count, posts_count)
VALUES (1, 1, 'Twitter', 10000, 200, 200);
INSERT INTO social_media_account (id, user_id, platform, followers_count, following_count, posts_count)
VALUES (2, 2, 'Instagram', 10000, 2000, 186);
INSERT INTO social_media_account (id, user_id, platform, followers_count, following_count, posts_count)
VALUES (3, 2, 'Facebook', 100000, 200, 100);

INSERT INTO analytics (id, social_account_id, reached_count, engaged_count, stories_count, follows_count, posts_count, save_count, comments_count, shares_count)
VALUES (2, 2, 800, 400, 100, 1000, 200, 1000, 900, 1000);
INSERT INTO analytics (id, social_account_id, reached_count, engaged_count, stories_count, follows_count, posts_count, save_count, comments_count, shares_count)
VALUES (5, 5, 5000, 20000, 50, 1230, 200, 1005, 1000, 20000);
INSERT INTO analytics (id, social_account_id, reached_count, engaged_count, stories_count, follows_count, posts_count, save_count, comments_count, shares_count)
VALUES (4, 4, 1000, 1800, 1000, 1000, 1000, 1900, 900, 343567);